FROM ubuntu

WORKDIR /usr/app

RUN apt-get update \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_10.x | bash \
  && apt-get install -y nodejs \
  && apt-get install -y git \
  && git clone https://github.com/docker-hy/backend-example-docker.git . \
  && npm i

ENV FRONT_URL=http://localhost:5000

EXPOSE 8000

ENTRYPOINT ["npm"]
CMD ["start"]
