FROM ruby:2.6.0

WORKDIR /usr/app

RUN apt-get update \
  && apt-get install -y curl \
  && curl -sL https://deb.nodesource.com/setup_10.x | bash \
  && apt-get install -y nodejs \
  && git clone https://github.com/docker-hy/rails-example-project.git . \
  && rm ./config/credentials.yml.enc \
  && bundle install

COPY ./master.key-1.14 ./config/master.key

# Create new credentials.yml.enc with our master.key
RUN EDITOR="mate --wait" bin/rails credentials:edit

RUN rails db:migrate RAILS_ENV=production \
  && rake assets:precompile

EXPOSE 3000

ENTRYPOINT ["rails"]
CMD ["s", "-e", "production"]
